[package]
name = "rfd"
version = "0.1.0"
authors = ["Poly <bartek.marynczak@op.pl>", "Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.80"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
objc_id = "0.1.1"
block = "0.1.6"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["commdlg","combaseapi","objbase","shobjidl"] }
wio = "0.2.2"

[target.'cfg(target_os = "linux")'.dependencies]
gtk-sys = "0.10.0"
glib-sys = "0.10.1"

[[example]]
name = "pick_file"
[[example]]
name = "pick_file_filter"
[[example]]
name = "pick_multiple"
[[example]]
name = "pick_folder"
[[example]]
name = "save"

[dev-dependencies]
winit="*"
