[package]
name = "rfd"
version = "0.0.3"
edition = "2018"

authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
description = "Rusty File Dialog"
keywords = ["file","ui","dialog"]
license = "MIT"
repository = "https://github.com/PolyMeilex/rfd"
documentation = "https://docs.rs/rfd"

[dev-dependencies]
futures="0.3.10"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
block="*"
cocoa-foundation= "0.1.0"


[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["combaseapi","objbase","shobjidl","shellapi"] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk-sys = "0.10.0"
glib-sys = "0.10.1"
gobject-sys = "0.10.0"
lazy_static = "1.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen= "0.2.69"
js-sys= "0.3.46"
web-sys={ version = "0.3.46", features = [
  'Document',
  'Element',
  'HtmlInputElement',
  'HtmlButtonElement',
  'Window',
  'File',
  'FileList',
  'FileReader',
] }
wasm-bindgen-futures = "0.4.19"


[[example]]
name = "simple"
[[example]]
name = "async"

[package.metadata.docs.rs]
all-features = true
