[package]
name = "rfd"
version = "0.1.0"
authors = ["Poly <bartek.marynczak@op.pl>", "Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"


[features]
native-file-handle = []

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
cocoa-foundation="0.1.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["combaseapi","objbase","shobjidl","shellapi"] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk-sys = "0.10.0"
glib-sys = "0.10.1"
gobject-sys = "0.10.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen="0.2.69"
js-sys="*"
web-sys={version="0.3.46",features = [
  'Document',
  'Element',
  'HtmlInputElement',
  'HtmlButtonElement',
  'Window',
  'File',
  'FileList',
  'FileReader',
]}
wasm-bindgen-futures = "0.4.19"


[[example]]
name = "builder"
[[example]]
name = "pick_file"
[[example]]
name = "pick_multiple"
[[example]]
name = "pick_folder"
[[example]]
name = "save"