[package]
name = "wasm-example"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

[dependencies]
rfd={path="../../"}
web-sys={version="0.3.46",features = [
  'Document',
  'Window',
]}

winit = { version = "0.24.0", features = ["web-sys"] }